# Generated by Django 5.2.3 on 2025-06-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='UserCoinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
