# Generated by Django 5.2.3 on 2025-06-27 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0003_siteinspection_safetyobservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyobservation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_observations', to=settings.AUTH_USER_MODEL),
        ),
    ]
