# Generated by Django 5.2.3 on 2025-06-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0004_alter_safetyobservation_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinspection',
            options={'ordering': ['-date']},
        ),
    ]
