# Generated by Django 5.2.3 on 2025-06-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0005_alter_siteinspection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyobservation',
            name='structured_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
