# Generated by Django 5.2.3 on 2025-06-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0006_safetyobservation_structured_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinspection',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteinspection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
