# Generated by Django 5.2.3 on 2025-06-29 05:09

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0007_siteinspection_completed_siteinspection_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumplan',
            options={'ordering': ['duration_days'], 'verbose_name': 'Premium Plan', 'verbose_name_plural': 'Premium Plans'},
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Plan Description'),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features for this plan', verbose_name='Plan Features'),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='coin_bonus',
            field=models.PositiveIntegerField(default=0, verbose_name='Coin Bonus'),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='duration_days',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration in Days'),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='name',
            field=models.CharField(choices=[('trial', 'Trial'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=50, unique=True, verbose_name='Plan Type'),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
    ]
