# Generated by Django 5.2.3 on 2025-06-29 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0008_alter_premiumplan_options_premiumplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumprofile',
            options={'verbose_name': 'Premium Profile', 'verbose_name_plural': 'Premium Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_end_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_start_date',
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
