# Generated by Django 5.2.3 on 2025-06-29 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0009_alter_premiumprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumprofile',
            options={'ordering': ['-start_date'], 'verbose_name': 'Premium Profile', 'verbose_name_plural': 'Premium Profiles'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_premium',
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='auto_renewal',
            field=models.BooleanField(default=True, verbose_name='Auto Renewal'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrsafe_app.premiumplan', verbose_name='Subscription Plan'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='premium_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Premium Code'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='trial_used',
            field=models.BooleanField(default=False, verbose_name='Trial Used'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
