# Generated by Django 5.2.3 on 2025-06-29 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0010_alter_premiumprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumprofile',
            options={'ordering': ['-start_date'], 'verbose_name': 'Premium Membership', 'verbose_name_plural': 'Premium Memberships'},
        ),
        migrations.AddField(
            model_name='premiumprofile',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Payment'),
        ),
        migrations.AddField(
            model_name='premiumprofile',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='auto_renewal',
            field=models.BooleanField(default=True, verbose_name='Auto-Renewal'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Membership End'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='premium_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Activation Code'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Membership Start'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='trial_used',
            field=models.BooleanField(default=False, verbose_name='Trial Period Used'),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddIndex(
            model_name='premiumprofile',
            index=models.Index(fields=['is_active', 'end_date'], name='mrsafe_app__is_acti_97f8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumprofile',
            index=models.Index(fields=['user', 'trial_used'], name='mrsafe_app__user_id_8ba971_idx'),
        ),
    ]
