# Generated by Django 5.2.3 on 2025-06-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0011_alter_premiumprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
