# Generated by Django 5.2.3 on 2025-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0012_alter_premiumplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumplan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
