# Generated by Django 5.2.3 on 2025-06-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrsafe_app', '0013_premiumplan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumplan',
            name='slug',
        ),
    ]
